// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.2
// source: importer.proto

package importer

import (
	v2 "github.com/PlakarKorp/integration-grpc/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Options struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os             string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch           string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Cwd            string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Maxconcurrency int64                  `protobuf:"varint,5,opt,name=maxconcurrency,proto3" json:"maxconcurrency,omitempty"`
	Excludes       []string               `protobuf:"bytes,6,rep,name=excludes,proto3" json:"excludes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_importer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Options) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Options) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Options) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Options) GetMaxconcurrency() int64 {
	if x != nil {
		return x.Maxconcurrency
	}
	return 0
}

func (x *Options) GetExcludes() []string {
	if x != nil {
		return x.Excludes
	}
	return nil
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *Options               `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	Proto         string                 `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_importer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequest) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *InitRequest) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Root          string                 `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_importer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{2}
}

func (x *InitResponse) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *InitResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InitResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *InitResponse) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_importer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{3}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_importer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{4}
}

type ImportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *v2.Result             `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRequest) Reset() {
	*x = ImportRequest{}
	mi := &file_importer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRequest) ProtoMessage() {}

func (x *ImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRequest.ProtoReflect.Descriptor instead.
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{5}
}

func (x *ImportRequest) GetResult() *v2.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type ImportResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Record *v2.Record             `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	// signals that the importer is done sending records, will just wait
	// for the acknowledgments.  result will be ignored if this is set.
	Finished      bool `protobuf:"varint,2,opt,name=finished,proto3" json:"finished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportResponse) Reset() {
	*x = ImportResponse{}
	mi := &file_importer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResponse) ProtoMessage() {}

func (x *ImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResponse.ProtoReflect.Descriptor instead.
func (*ImportResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{6}
}

func (x *ImportResponse) GetRecord() *v2.Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *ImportResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *v2.Record             `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_importer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{7}
}

func (x *OpenRequest) GetRecord() *v2.Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_importer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{8}
}

func (x *OpenResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_importer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{9}
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_importer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_importer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_importer_proto_rawDescGZIP(), []int{10}
}

var File_importer_proto protoreflect.FileDescriptor

const file_importer_proto_rawDesc = "" +
	"\n" +
	"\x0eimporter.proto\x12\x12plakar.importer.v2\x1a\x10connectors.proto\"\x9f\x01\n" +
	"\aOptions\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12&\n" +
	"\x0emaxconcurrency\x18\x05 \x01(\x03R\x0emaxconcurrency\x12\x1a\n" +
	"\bexcludes\x18\x06 \x03(\tR\bexcludes\"\xda\x01\n" +
	"\vInitRequest\x125\n" +
	"\aoptions\x18\x01 \x01(\v2\x1b.plakar.importer.v2.OptionsR\aoptions\x12\x14\n" +
	"\x05proto\x18\x02 \x01(\tR\x05proto\x12C\n" +
	"\x06config\x18\x03 \x03(\v2+.plakar.importer.v2.InitRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\fInitResponse\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04root\x18\x03 \x01(\tR\x04root\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"B\n" +
	"\rImportRequest\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.plakar.connectors.ResultR\x06result\"_\n" +
	"\x0eImportResponse\x121\n" +
	"\x06record\x18\x01 \x01(\v2\x19.plakar.connectors.RecordR\x06record\x12\x1a\n" +
	"\bfinished\x18\x02 \x01(\bR\bfinished\"@\n" +
	"\vOpenRequest\x121\n" +
	"\x06record\x18\x01 \x01(\v2\x19.plakar.connectors.RecordR\x06record\"$\n" +
	"\fOpenResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"\x0e\n" +
	"\fCloseRequest\"\x0f\n" +
	"\rCloseResponse2\x90\x03\n" +
	"\bImporter\x12I\n" +
	"\x04Init\x12\x1f.plakar.importer.v2.InitRequest\x1a .plakar.importer.v2.InitResponse\x12I\n" +
	"\x04Ping\x12\x1f.plakar.importer.v2.PingRequest\x1a .plakar.importer.v2.PingResponse\x12S\n" +
	"\x06Import\x12!.plakar.importer.v2.ImportRequest\x1a\".plakar.importer.v2.ImportResponse(\x010\x01\x12K\n" +
	"\x04Open\x12\x1f.plakar.importer.v2.OpenRequest\x1a .plakar.importer.v2.OpenResponse0\x01\x12L\n" +
	"\x05Close\x12 .plakar.importer.v2.CloseRequest\x1a!.plakar.importer.v2.CloseResponseb\x06proto3"

var (
	file_importer_proto_rawDescOnce sync.Once
	file_importer_proto_rawDescData []byte
)

func file_importer_proto_rawDescGZIP() []byte {
	file_importer_proto_rawDescOnce.Do(func() {
		file_importer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_importer_proto_rawDesc), len(file_importer_proto_rawDesc)))
	})
	return file_importer_proto_rawDescData
}

var file_importer_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_importer_proto_goTypes = []any{
	(*Options)(nil),        // 0: plakar.importer.v2.Options
	(*InitRequest)(nil),    // 1: plakar.importer.v2.InitRequest
	(*InitResponse)(nil),   // 2: plakar.importer.v2.InitResponse
	(*PingRequest)(nil),    // 3: plakar.importer.v2.PingRequest
	(*PingResponse)(nil),   // 4: plakar.importer.v2.PingResponse
	(*ImportRequest)(nil),  // 5: plakar.importer.v2.ImportRequest
	(*ImportResponse)(nil), // 6: plakar.importer.v2.ImportResponse
	(*OpenRequest)(nil),    // 7: plakar.importer.v2.OpenRequest
	(*OpenResponse)(nil),   // 8: plakar.importer.v2.OpenResponse
	(*CloseRequest)(nil),   // 9: plakar.importer.v2.CloseRequest
	(*CloseResponse)(nil),  // 10: plakar.importer.v2.CloseResponse
	nil,                    // 11: plakar.importer.v2.InitRequest.ConfigEntry
	(*v2.Result)(nil),      // 12: plakar.connectors.Result
	(*v2.Record)(nil),      // 13: plakar.connectors.Record
}
var file_importer_proto_depIdxs = []int32{
	0,  // 0: plakar.importer.v2.InitRequest.options:type_name -> plakar.importer.v2.Options
	11, // 1: plakar.importer.v2.InitRequest.config:type_name -> plakar.importer.v2.InitRequest.ConfigEntry
	12, // 2: plakar.importer.v2.ImportRequest.result:type_name -> plakar.connectors.Result
	13, // 3: plakar.importer.v2.ImportResponse.record:type_name -> plakar.connectors.Record
	13, // 4: plakar.importer.v2.OpenRequest.record:type_name -> plakar.connectors.Record
	1,  // 5: plakar.importer.v2.Importer.Init:input_type -> plakar.importer.v2.InitRequest
	3,  // 6: plakar.importer.v2.Importer.Ping:input_type -> plakar.importer.v2.PingRequest
	5,  // 7: plakar.importer.v2.Importer.Import:input_type -> plakar.importer.v2.ImportRequest
	7,  // 8: plakar.importer.v2.Importer.Open:input_type -> plakar.importer.v2.OpenRequest
	9,  // 9: plakar.importer.v2.Importer.Close:input_type -> plakar.importer.v2.CloseRequest
	2,  // 10: plakar.importer.v2.Importer.Init:output_type -> plakar.importer.v2.InitResponse
	4,  // 11: plakar.importer.v2.Importer.Ping:output_type -> plakar.importer.v2.PingResponse
	6,  // 12: plakar.importer.v2.Importer.Import:output_type -> plakar.importer.v2.ImportResponse
	8,  // 13: plakar.importer.v2.Importer.Open:output_type -> plakar.importer.v2.OpenResponse
	10, // 14: plakar.importer.v2.Importer.Close:output_type -> plakar.importer.v2.CloseResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_importer_proto_init() }
func file_importer_proto_init() {
	if File_importer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_importer_proto_rawDesc), len(file_importer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_importer_proto_goTypes,
		DependencyIndexes: file_importer_proto_depIdxs,
		MessageInfos:      file_importer_proto_msgTypes,
	}.Build()
	File_importer_proto = out.File
	file_importer_proto_goTypes = nil
	file_importer_proto_depIdxs = nil
}
