name: docker
display_name: Docker
description: Integration providing import capabilities from Docker images.
version: v.1.0.0-beta
connectors:
- type: importer
  executable: dockerImporter
  homepage: https://github.com/PlakarKorp/integration-docker
  license: ISC
  protocols: [docker]
