// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: connectors.proto

package integration_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtendedAttributeType int32

const (
	ExtendedAttributeType_EXTENDED_ATTRIBUTE_TYPE_UNSPECIFIED ExtendedAttributeType = 0
	ExtendedAttributeType_EXTENDED_ATTRIBUTE_TYPE_EXTENDED    ExtendedAttributeType = 1
	ExtendedAttributeType_EXTENDED_ATTRIBUTE_TYPE_ADS         ExtendedAttributeType = 2
)

// Enum value maps for ExtendedAttributeType.
var (
	ExtendedAttributeType_name = map[int32]string{
		0: "EXTENDED_ATTRIBUTE_TYPE_UNSPECIFIED",
		1: "EXTENDED_ATTRIBUTE_TYPE_EXTENDED",
		2: "EXTENDED_ATTRIBUTE_TYPE_ADS",
	}
	ExtendedAttributeType_value = map[string]int32{
		"EXTENDED_ATTRIBUTE_TYPE_UNSPECIFIED": 0,
		"EXTENDED_ATTRIBUTE_TYPE_EXTENDED":    1,
		"EXTENDED_ATTRIBUTE_TYPE_ADS":         2,
	}
)

func (x ExtendedAttributeType) Enum() *ExtendedAttributeType {
	p := new(ExtendedAttributeType)
	*p = x
	return p
}

func (x ExtendedAttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtendedAttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_connectors_proto_enumTypes[0].Descriptor()
}

func (ExtendedAttributeType) Type() protoreflect.EnumType {
	return &file_connectors_proto_enumTypes[0]
}

func (x ExtendedAttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtendedAttributeType.Descriptor instead.
func (ExtendedAttributeType) EnumDescriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{0}
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	Dev           uint64                 `protobuf:"varint,5,opt,name=dev,proto3" json:"dev,omitempty"`
	Ino           uint64                 `protobuf:"varint,6,opt,name=ino,proto3" json:"ino,omitempty"`
	Uid           uint64                 `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint64                 `protobuf:"varint,8,opt,name=gid,proto3" json:"gid,omitempty"`
	Nlink         uint32                 `protobuf:"varint,9,opt,name=nlink,proto3" json:"nlink,omitempty"` // but is really uint16
	Username      string                 `protobuf:"bytes,10,opt,name=username,proto3" json:"username,omitempty"`
	Groupname     string                 `protobuf:"bytes,11,opt,name=groupname,proto3" json:"groupname,omitempty"`
	Flags         uint32                 `protobuf:"varint,12,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_connectors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileInfo) GetModTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *FileInfo) GetDev() uint64 {
	if x != nil {
		return x.Dev
	}
	return 0
}

func (x *FileInfo) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *FileInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *FileInfo) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *FileInfo) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *FileInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FileInfo) GetGroupname() string {
	if x != nil {
		return x.Groupname
	}
	return ""
}

func (x *FileInfo) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type Record struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HasReader          bool                   `protobuf:"varint,1,opt,name=hasReader,proto3" json:"hasReader,omitempty"`
	Pathname           string                 `protobuf:"bytes,2,opt,name=pathname,proto3" json:"pathname,omitempty"`
	Error              string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	IsXattr            bool                   `protobuf:"varint,4,opt,name=isXattr,proto3" json:"isXattr,omitempty"`
	XattrName          string                 `protobuf:"bytes,5,opt,name=xattrName,proto3" json:"xattrName,omitempty"`
	XattrType          ExtendedAttributeType  `protobuf:"varint,6,opt,name=xattrType,proto3,enum=plakar.connectors.ExtendedAttributeType" json:"xattrType,omitempty"`
	Target             string                 `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	FileInfo           *FileInfo              `protobuf:"bytes,8,opt,name=fileInfo,proto3" json:"fileInfo,omitempty"`
	ExtendedAttributes []string               `protobuf:"bytes,9,rep,name=extendedAttributes,proto3" json:"extendedAttributes,omitempty"`
	FileAttributes     uint32                 `protobuf:"varint,10,opt,name=fileAttributes,proto3" json:"fileAttributes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_connectors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetHasReader() bool {
	if x != nil {
		return x.HasReader
	}
	return false
}

func (x *Record) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

func (x *Record) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Record) GetIsXattr() bool {
	if x != nil {
		return x.IsXattr
	}
	return false
}

func (x *Record) GetXattrName() string {
	if x != nil {
		return x.XattrName
	}
	return ""
}

func (x *Record) GetXattrType() ExtendedAttributeType {
	if x != nil {
		return x.XattrType
	}
	return ExtendedAttributeType_EXTENDED_ATTRIBUTE_TYPE_UNSPECIFIED
}

func (x *Record) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Record) GetFileInfo() *FileInfo {
	if x != nil {
		return x.FileInfo
	}
	return nil
}

func (x *Record) GetExtendedAttributes() []string {
	if x != nil {
		return x.ExtendedAttributes
	}
	return nil
}

func (x *Record) GetFileAttributes() uint32 {
	if x != nil {
		return x.FileAttributes
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Record                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_connectors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_connectors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_connectors_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetHeader() *Record {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_connectors_proto protoreflect.FileDescriptor

const file_connectors_proto_rawDesc = "" +
	"\n" +
	"\x10connectors.proto\x12\x11plakar.connectors\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x02\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x125\n" +
	"\bmod_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\x12\x10\n" +
	"\x03dev\x18\x05 \x01(\x04R\x03dev\x12\x10\n" +
	"\x03ino\x18\x06 \x01(\x04R\x03ino\x12\x10\n" +
	"\x03uid\x18\a \x01(\x04R\x03uid\x12\x10\n" +
	"\x03gid\x18\b \x01(\x04R\x03gid\x12\x14\n" +
	"\x05nlink\x18\t \x01(\rR\x05nlink\x12\x1a\n" +
	"\busername\x18\n" +
	" \x01(\tR\busername\x12\x1c\n" +
	"\tgroupname\x18\v \x01(\tR\tgroupname\x12\x14\n" +
	"\x05flags\x18\f \x01(\rR\x05flags\"\x81\x03\n" +
	"\x06Record\x12\x1c\n" +
	"\thasReader\x18\x01 \x01(\bR\thasReader\x12\x1a\n" +
	"\bpathname\x18\x02 \x01(\tR\bpathname\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\aisXattr\x18\x04 \x01(\bR\aisXattr\x12\x1c\n" +
	"\txattrName\x18\x05 \x01(\tR\txattrName\x12F\n" +
	"\txattrType\x18\x06 \x01(\x0e2(.plakar.connectors.ExtendedAttributeTypeR\txattrType\x12\x16\n" +
	"\x06target\x18\a \x01(\tR\x06target\x127\n" +
	"\bfileInfo\x18\b \x01(\v2\x1b.plakar.connectors.FileInfoR\bfileInfo\x12.\n" +
	"\x12extendedAttributes\x18\t \x03(\tR\x12extendedAttributes\x12&\n" +
	"\x0efileAttributes\x18\n" +
	" \x01(\rR\x0efileAttributes\"Q\n" +
	"\x06Result\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x19.plakar.connectors.RecordR\x06header\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*\x87\x01\n" +
	"\x15ExtendedAttributeType\x12'\n" +
	"#EXTENDED_ATTRIBUTE_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" EXTENDED_ATTRIBUTE_TYPE_EXTENDED\x10\x01\x12\x1f\n" +
	"\x1bEXTENDED_ATTRIBUTE_TYPE_ADS\x10\x02B<Z:github.com/PlakarKorp/integration-grpc/v2;integration_grpcb\x06proto3"

var (
	file_connectors_proto_rawDescOnce sync.Once
	file_connectors_proto_rawDescData []byte
)

func file_connectors_proto_rawDescGZIP() []byte {
	file_connectors_proto_rawDescOnce.Do(func() {
		file_connectors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connectors_proto_rawDesc), len(file_connectors_proto_rawDesc)))
	})
	return file_connectors_proto_rawDescData
}

var file_connectors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_connectors_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_connectors_proto_goTypes = []any{
	(ExtendedAttributeType)(0),    // 0: plakar.connectors.ExtendedAttributeType
	(*FileInfo)(nil),              // 1: plakar.connectors.FileInfo
	(*Record)(nil),                // 2: plakar.connectors.Record
	(*Result)(nil),                // 3: plakar.connectors.Result
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_connectors_proto_depIdxs = []int32{
	4, // 0: plakar.connectors.FileInfo.mod_time:type_name -> google.protobuf.Timestamp
	0, // 1: plakar.connectors.Record.xattrType:type_name -> plakar.connectors.ExtendedAttributeType
	1, // 2: plakar.connectors.Record.fileInfo:type_name -> plakar.connectors.FileInfo
	2, // 3: plakar.connectors.Result.header:type_name -> plakar.connectors.Record
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_connectors_proto_init() }
func file_connectors_proto_init() {
	if File_connectors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connectors_proto_rawDesc), len(file_connectors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connectors_proto_goTypes,
		DependencyIndexes: file_connectors_proto_depIdxs,
		EnumInfos:         file_connectors_proto_enumTypes,
		MessageInfos:      file_connectors_proto_msgTypes,
	}.Build()
	File_connectors_proto = out.File
	file_connectors_proto_goTypes = nil
	file_connectors_proto_depIdxs = nil
}
