// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.2
// source: storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageResource int32

const (
	StorageResource_STORAGE_RESOURCE_UNDEFINED    StorageResource = 0
	StorageResource_STORAGE_RESOURCE_PACKFILE     StorageResource = 1
	StorageResource_STORAGE_RESOURCE_STATE        StorageResource = 2
	StorageResource_STORAGE_RESOURCE_LOCK         StorageResource = 3
	StorageResource_STORAGE_RESOURCE_ECC_PACKFILE StorageResource = 4
	StorageResource_STORAGE_RESOURCE_ECC_STATE    StorageResource = 5
)

// Enum value maps for StorageResource.
var (
	StorageResource_name = map[int32]string{
		0: "STORAGE_RESOURCE_UNDEFINED",
		1: "STORAGE_RESOURCE_PACKFILE",
		2: "STORAGE_RESOURCE_STATE",
		3: "STORAGE_RESOURCE_LOCK",
		4: "STORAGE_RESOURCE_ECC_PACKFILE",
		5: "STORAGE_RESOURCE_ECC_STATE",
	}
	StorageResource_value = map[string]int32{
		"STORAGE_RESOURCE_UNDEFINED":    0,
		"STORAGE_RESOURCE_PACKFILE":     1,
		"STORAGE_RESOURCE_STATE":        2,
		"STORAGE_RESOURCE_LOCK":         3,
		"STORAGE_RESOURCE_ECC_PACKFILE": 4,
		"STORAGE_RESOURCE_ECC_STATE":    5,
	}
)

func (x StorageResource) Enum() *StorageResource {
	p := new(StorageResource)
	*p = x
	return p
}

func (x StorageResource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageResource) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proto_enumTypes[0].Descriptor()
}

func (StorageResource) Type() protoreflect.EnumType {
	return &file_storage_proto_enumTypes[0]
}

func (x StorageResource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageResource.Descriptor instead.
func (StorageResource) EnumDescriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proto         string                 `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Root          string                 `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	Flags         uint32                 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *InitResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InitResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *InitResponse) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *OpenResponse) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

type ModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeRequest) Reset() {
	*x = ModeRequest{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeRequest) ProtoMessage() {}

func (x *ModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeRequest.ProtoReflect.Descriptor instead.
func (*ModeRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

type ModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          int32                  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeResponse) Reset() {
	*x = ModeResponse{}
	mi := &file_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeResponse) ProtoMessage() {}

func (x *ModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeResponse.ProtoReflect.Descriptor instead.
func (*ModeResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{9}
}

func (x *ModeResponse) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{10}
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{11}
}

type SizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeRequest) Reset() {
	*x = SizeRequest{}
	mi := &file_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeRequest) ProtoMessage() {}

func (x *SizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeRequest.ProtoReflect.Descriptor instead.
func (*SizeRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{12}
}

type SizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeResponse) Reset() {
	*x = SizeResponse{}
	mi := &file_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeResponse) ProtoMessage() {}

func (x *SizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeResponse.ProtoReflect.Descriptor instead.
func (*SizeResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{13}
}

func (x *SizeResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          StorageResource        `protobuf:"varint,1,opt,name=type,proto3,enum=plakar.store.v2.StorageResource" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{14}
}

func (x *ListRequest) GetType() StorageResource {
	if x != nil {
		return x.Type
	}
	return StorageResource_STORAGE_RESOURCE_UNDEFINED
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Macs          [][]byte               `protobuf:"bytes,1,rep,name=macs,proto3" json:"macs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{15}
}

func (x *ListResponse) GetMacs() [][]byte {
	if x != nil {
		return x.Macs
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           []byte                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Type          StorageResource        `protobuf:"varint,2,opt,name=type,proto3,enum=plakar.store.v2.StorageResource" json:"type,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{16}
}

func (x *PutRequest) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *PutRequest) GetType() StorageResource {
	if x != nil {
		return x.Type
	}
	return StorageResource_STORAGE_RESOURCE_UNDEFINED
}

func (x *PutRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{17}
}

func (x *PutResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           []byte                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Type          StorageResource        `protobuf:"varint,2,opt,name=type,proto3,enum=plakar.store.v2.StorageResource" json:"type,omitempty"`
	Range         *GetRequest_Range      `protobuf:"bytes,3,opt,name=range,proto3,oneof" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{18}
}

func (x *GetRequest) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *GetRequest) GetType() StorageResource {
	if x != nil {
		return x.Type
	}
	return StorageResource_STORAGE_RESOURCE_UNDEFINED
}

func (x *GetRequest) GetRange() *GetRequest_Range {
	if x != nil {
		return x.Range
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_storage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{19}
}

func (x *GetResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           []byte                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Type          StorageResource        `protobuf:"varint,2,opt,name=type,proto3,enum=plakar.store.v2.StorageResource" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_storage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteRequest) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *DeleteRequest) GetType() StorageResource {
	if x != nil {
		return x.Type
	}
	return StorageResource_STORAGE_RESOURCE_UNDEFINED
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_storage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{21}
}

type GetRequest_Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint32                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest_Range) Reset() {
	*x = GetRequest_Range{}
	mi := &file_storage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest_Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest_Range) ProtoMessage() {}

func (x *GetRequest_Range) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest_Range.ProtoReflect.Descriptor instead.
func (*GetRequest_Range) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{18, 0}
}

func (x *GetRequest_Range) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetRequest_Range) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\x0fplakar.store.v2\"\xa0\x01\n" +
	"\vInitRequest\x12\x14\n" +
	"\x05proto\x18\x01 \x01(\tR\x05proto\x12@\n" +
	"\x06config\x18\x02 \x03(\v2(.plakar.store.v2.InitRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\fInitResponse\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04root\x18\x03 \x01(\tR\x04root\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\"'\n" +
	"\rCreateRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\"\x10\n" +
	"\x0eCreateResponse\"\r\n" +
	"\vOpenRequest\"&\n" +
	"\fOpenResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"\r\n" +
	"\vModeRequest\"\"\n" +
	"\fModeResponse\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\x05R\x04mode\"\x0e\n" +
	"\fCloseRequest\"\x0f\n" +
	"\rCloseResponse\"\r\n" +
	"\vSizeRequest\"\"\n" +
	"\fSizeResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\"C\n" +
	"\vListRequest\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .plakar.store.v2.StorageResourceR\x04type\"\"\n" +
	"\fListResponse\x12\x12\n" +
	"\x04macs\x18\x01 \x03(\fR\x04macs\"j\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\fR\x03mac\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .plakar.store.v2.StorageResourceR\x04type\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\fR\x05chunk\"2\n" +
	"\vPutResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\"\xd5\x01\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\fR\x03mac\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .plakar.store.v2.StorageResourceR\x04type\x12<\n" +
	"\x05range\x18\x03 \x01(\v2!.plakar.store.v2.GetRequest.RangeH\x00R\x05range\x88\x01\x01\x1a7\n" +
	"\x05Range\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\rR\x06lengthB\b\n" +
	"\x06_range\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"W\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\fR\x03mac\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .plakar.store.v2.StorageResourceR\x04type\"\x10\n" +
	"\x0eDeleteResponse*\xca\x01\n" +
	"\x0fStorageResource\x12\x1e\n" +
	"\x1aSTORAGE_RESOURCE_UNDEFINED\x10\x00\x12\x1d\n" +
	"\x19STORAGE_RESOURCE_PACKFILE\x10\x01\x12\x1a\n" +
	"\x16STORAGE_RESOURCE_STATE\x10\x02\x12\x19\n" +
	"\x15STORAGE_RESOURCE_LOCK\x10\x03\x12!\n" +
	"\x1dSTORAGE_RESOURCE_ECC_PACKFILE\x10\x04\x12\x1e\n" +
	"\x1aSTORAGE_RESOURCE_ECC_STATE\x10\x052\x8b\x06\n" +
	"\x05Store\x12C\n" +
	"\x04Init\x12\x1c.plakar.store.v2.InitRequest\x1a\x1d.plakar.store.v2.InitResponse\x12I\n" +
	"\x06Create\x12\x1e.plakar.store.v2.CreateRequest\x1a\x1f.plakar.store.v2.CreateResponse\x12C\n" +
	"\x04Open\x12\x1c.plakar.store.v2.OpenRequest\x1a\x1d.plakar.store.v2.OpenResponse\x12C\n" +
	"\x04Ping\x12\x1c.plakar.store.v2.PingRequest\x1a\x1d.plakar.store.v2.PingResponse\x12C\n" +
	"\x04Mode\x12\x1c.plakar.store.v2.ModeRequest\x1a\x1d.plakar.store.v2.ModeResponse\x12C\n" +
	"\x04Size\x12\x1c.plakar.store.v2.SizeRequest\x1a\x1d.plakar.store.v2.SizeResponse\x12C\n" +
	"\x04List\x12\x1c.plakar.store.v2.ListRequest\x1a\x1d.plakar.store.v2.ListResponse\x12B\n" +
	"\x03Put\x12\x1b.plakar.store.v2.PutRequest\x1a\x1c.plakar.store.v2.PutResponse(\x01\x12B\n" +
	"\x03Get\x12\x1b.plakar.store.v2.GetRequest\x1a\x1c.plakar.store.v2.GetResponse0\x01\x12I\n" +
	"\x06Delete\x12\x1e.plakar.store.v2.DeleteRequest\x1a\x1f.plakar.store.v2.DeleteResponse\x12F\n" +
	"\x05Close\x12\x1d.plakar.store.v2.CloseRequest\x1a\x1e.plakar.store.v2.CloseResponseb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_storage_proto_goTypes = []any{
	(StorageResource)(0),     // 0: plakar.store.v2.StorageResource
	(*InitRequest)(nil),      // 1: plakar.store.v2.InitRequest
	(*InitResponse)(nil),     // 2: plakar.store.v2.InitResponse
	(*CreateRequest)(nil),    // 3: plakar.store.v2.CreateRequest
	(*CreateResponse)(nil),   // 4: plakar.store.v2.CreateResponse
	(*OpenRequest)(nil),      // 5: plakar.store.v2.OpenRequest
	(*OpenResponse)(nil),     // 6: plakar.store.v2.OpenResponse
	(*PingRequest)(nil),      // 7: plakar.store.v2.PingRequest
	(*PingResponse)(nil),     // 8: plakar.store.v2.PingResponse
	(*ModeRequest)(nil),      // 9: plakar.store.v2.ModeRequest
	(*ModeResponse)(nil),     // 10: plakar.store.v2.ModeResponse
	(*CloseRequest)(nil),     // 11: plakar.store.v2.CloseRequest
	(*CloseResponse)(nil),    // 12: plakar.store.v2.CloseResponse
	(*SizeRequest)(nil),      // 13: plakar.store.v2.SizeRequest
	(*SizeResponse)(nil),     // 14: plakar.store.v2.SizeResponse
	(*ListRequest)(nil),      // 15: plakar.store.v2.ListRequest
	(*ListResponse)(nil),     // 16: plakar.store.v2.ListResponse
	(*PutRequest)(nil),       // 17: plakar.store.v2.PutRequest
	(*PutResponse)(nil),      // 18: plakar.store.v2.PutResponse
	(*GetRequest)(nil),       // 19: plakar.store.v2.GetRequest
	(*GetResponse)(nil),      // 20: plakar.store.v2.GetResponse
	(*DeleteRequest)(nil),    // 21: plakar.store.v2.DeleteRequest
	(*DeleteResponse)(nil),   // 22: plakar.store.v2.DeleteResponse
	nil,                      // 23: plakar.store.v2.InitRequest.ConfigEntry
	(*GetRequest_Range)(nil), // 24: plakar.store.v2.GetRequest.Range
}
var file_storage_proto_depIdxs = []int32{
	23, // 0: plakar.store.v2.InitRequest.config:type_name -> plakar.store.v2.InitRequest.ConfigEntry
	0,  // 1: plakar.store.v2.ListRequest.type:type_name -> plakar.store.v2.StorageResource
	0,  // 2: plakar.store.v2.PutRequest.type:type_name -> plakar.store.v2.StorageResource
	0,  // 3: plakar.store.v2.GetRequest.type:type_name -> plakar.store.v2.StorageResource
	24, // 4: plakar.store.v2.GetRequest.range:type_name -> plakar.store.v2.GetRequest.Range
	0,  // 5: plakar.store.v2.DeleteRequest.type:type_name -> plakar.store.v2.StorageResource
	1,  // 6: plakar.store.v2.Store.Init:input_type -> plakar.store.v2.InitRequest
	3,  // 7: plakar.store.v2.Store.Create:input_type -> plakar.store.v2.CreateRequest
	5,  // 8: plakar.store.v2.Store.Open:input_type -> plakar.store.v2.OpenRequest
	7,  // 9: plakar.store.v2.Store.Ping:input_type -> plakar.store.v2.PingRequest
	9,  // 10: plakar.store.v2.Store.Mode:input_type -> plakar.store.v2.ModeRequest
	13, // 11: plakar.store.v2.Store.Size:input_type -> plakar.store.v2.SizeRequest
	15, // 12: plakar.store.v2.Store.List:input_type -> plakar.store.v2.ListRequest
	17, // 13: plakar.store.v2.Store.Put:input_type -> plakar.store.v2.PutRequest
	19, // 14: plakar.store.v2.Store.Get:input_type -> plakar.store.v2.GetRequest
	21, // 15: plakar.store.v2.Store.Delete:input_type -> plakar.store.v2.DeleteRequest
	11, // 16: plakar.store.v2.Store.Close:input_type -> plakar.store.v2.CloseRequest
	2,  // 17: plakar.store.v2.Store.Init:output_type -> plakar.store.v2.InitResponse
	4,  // 18: plakar.store.v2.Store.Create:output_type -> plakar.store.v2.CreateResponse
	6,  // 19: plakar.store.v2.Store.Open:output_type -> plakar.store.v2.OpenResponse
	8,  // 20: plakar.store.v2.Store.Ping:output_type -> plakar.store.v2.PingResponse
	10, // 21: plakar.store.v2.Store.Mode:output_type -> plakar.store.v2.ModeResponse
	14, // 22: plakar.store.v2.Store.Size:output_type -> plakar.store.v2.SizeResponse
	16, // 23: plakar.store.v2.Store.List:output_type -> plakar.store.v2.ListResponse
	18, // 24: plakar.store.v2.Store.Put:output_type -> plakar.store.v2.PutResponse
	20, // 25: plakar.store.v2.Store.Get:output_type -> plakar.store.v2.GetResponse
	22, // 26: plakar.store.v2.Store.Delete:output_type -> plakar.store.v2.DeleteResponse
	12, // 27: plakar.store.v2.Store.Close:output_type -> plakar.store.v2.CloseResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	file_storage_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		EnumInfos:         file_storage_proto_enumTypes,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
