// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.2
// source: exporter.proto

package exporter

import (
	v2 "github.com/PlakarKorp/integration-grpc/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Options struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Hostname       string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os             string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch           string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Cwd            string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Maxconcurrency int64                  `protobuf:"varint,5,opt,name=maxconcurrency,proto3" json:"maxconcurrency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_exporter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Options) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Options) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Options) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Options) GetMaxconcurrency() int64 {
	if x != nil {
		return x.Maxconcurrency
	}
	return 0
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *Options               `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	Proto         string                 `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_exporter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequest) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *InitRequest) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origin        string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Root          string                 `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_exporter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{2}
}

func (x *InitResponse) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *InitResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InitResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *InitResponse) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_exporter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{3}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_exporter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{4}
}

type ExportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Packet:
	//
	//	*ExportRequest_Record
	//	*ExportRequest_Chunk
	Packet        isExportRequest_Packet `protobuf_oneof:"packet"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_exporter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{5}
}

func (x *ExportRequest) GetPacket() isExportRequest_Packet {
	if x != nil {
		return x.Packet
	}
	return nil
}

func (x *ExportRequest) GetRecord() *v2.Record {
	if x != nil {
		if x, ok := x.Packet.(*ExportRequest_Record); ok {
			return x.Record
		}
	}
	return nil
}

func (x *ExportRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Packet.(*ExportRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isExportRequest_Packet interface {
	isExportRequest_Packet()
}

type ExportRequest_Record struct {
	Record *v2.Record `protobuf:"bytes,1,opt,name=record,proto3,oneof"`
}

type ExportRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*ExportRequest_Record) isExportRequest_Packet() {}

func (*ExportRequest_Chunk) isExportRequest_Packet() {}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *v2.Result             `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_exporter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{6}
}

func (x *ExportResponse) GetResult() *v2.Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_exporter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{7}
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_exporter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exporter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_exporter_proto_rawDescGZIP(), []int{8}
}

var File_exporter_proto protoreflect.FileDescriptor

const file_exporter_proto_rawDesc = "" +
	"\n" +
	"\x0eexporter.proto\x12\x12plakar.exporter.v2\x1a\x10connectors.proto\"\x83\x01\n" +
	"\aOptions\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12&\n" +
	"\x0emaxconcurrency\x18\x05 \x01(\x03R\x0emaxconcurrency\"\xda\x01\n" +
	"\vInitRequest\x125\n" +
	"\aoptions\x18\x01 \x01(\v2\x1b.plakar.exporter.v2.OptionsR\aoptions\x12\x14\n" +
	"\x05proto\x18\x02 \x01(\tR\x05proto\x12C\n" +
	"\x06config\x18\x03 \x03(\v2+.plakar.exporter.v2.InitRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\fInitResponse\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04root\x18\x03 \x01(\tR\x04root\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"f\n" +
	"\rExportRequest\x123\n" +
	"\x06record\x18\x01 \x01(\v2\x19.plakar.connectors.RecordH\x00R\x06record\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\b\n" +
	"\x06packet\"C\n" +
	"\x0eExportResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.plakar.connectors.ResultR\x06result\"\x0e\n" +
	"\fCloseRequest\"\x0f\n" +
	"\rCloseResponse2\xc3\x02\n" +
	"\bExporter\x12I\n" +
	"\x04Init\x12\x1f.plakar.exporter.v2.InitRequest\x1a .plakar.exporter.v2.InitResponse\x12I\n" +
	"\x04Ping\x12\x1f.plakar.exporter.v2.PingRequest\x1a .plakar.exporter.v2.PingResponse\x12S\n" +
	"\x06Export\x12!.plakar.exporter.v2.ExportRequest\x1a\".plakar.exporter.v2.ExportResponse(\x010\x01\x12L\n" +
	"\x05Close\x12 .plakar.exporter.v2.CloseRequest\x1a!.plakar.exporter.v2.CloseResponseb\x06proto3"

var (
	file_exporter_proto_rawDescOnce sync.Once
	file_exporter_proto_rawDescData []byte
)

func file_exporter_proto_rawDescGZIP() []byte {
	file_exporter_proto_rawDescOnce.Do(func() {
		file_exporter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exporter_proto_rawDesc), len(file_exporter_proto_rawDesc)))
	})
	return file_exporter_proto_rawDescData
}

var file_exporter_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_exporter_proto_goTypes = []any{
	(*Options)(nil),        // 0: plakar.exporter.v2.Options
	(*InitRequest)(nil),    // 1: plakar.exporter.v2.InitRequest
	(*InitResponse)(nil),   // 2: plakar.exporter.v2.InitResponse
	(*PingRequest)(nil),    // 3: plakar.exporter.v2.PingRequest
	(*PingResponse)(nil),   // 4: plakar.exporter.v2.PingResponse
	(*ExportRequest)(nil),  // 5: plakar.exporter.v2.ExportRequest
	(*ExportResponse)(nil), // 6: plakar.exporter.v2.ExportResponse
	(*CloseRequest)(nil),   // 7: plakar.exporter.v2.CloseRequest
	(*CloseResponse)(nil),  // 8: plakar.exporter.v2.CloseResponse
	nil,                    // 9: plakar.exporter.v2.InitRequest.ConfigEntry
	(*v2.Record)(nil),      // 10: plakar.connectors.Record
	(*v2.Result)(nil),      // 11: plakar.connectors.Result
}
var file_exporter_proto_depIdxs = []int32{
	0,  // 0: plakar.exporter.v2.InitRequest.options:type_name -> plakar.exporter.v2.Options
	9,  // 1: plakar.exporter.v2.InitRequest.config:type_name -> plakar.exporter.v2.InitRequest.ConfigEntry
	10, // 2: plakar.exporter.v2.ExportRequest.record:type_name -> plakar.connectors.Record
	11, // 3: plakar.exporter.v2.ExportResponse.result:type_name -> plakar.connectors.Result
	1,  // 4: plakar.exporter.v2.Exporter.Init:input_type -> plakar.exporter.v2.InitRequest
	3,  // 5: plakar.exporter.v2.Exporter.Ping:input_type -> plakar.exporter.v2.PingRequest
	5,  // 6: plakar.exporter.v2.Exporter.Export:input_type -> plakar.exporter.v2.ExportRequest
	7,  // 7: plakar.exporter.v2.Exporter.Close:input_type -> plakar.exporter.v2.CloseRequest
	2,  // 8: plakar.exporter.v2.Exporter.Init:output_type -> plakar.exporter.v2.InitResponse
	4,  // 9: plakar.exporter.v2.Exporter.Ping:output_type -> plakar.exporter.v2.PingResponse
	6,  // 10: plakar.exporter.v2.Exporter.Export:output_type -> plakar.exporter.v2.ExportResponse
	8,  // 11: plakar.exporter.v2.Exporter.Close:output_type -> plakar.exporter.v2.CloseResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_exporter_proto_init() }
func file_exporter_proto_init() {
	if File_exporter_proto != nil {
		return
	}
	file_exporter_proto_msgTypes[5].OneofWrappers = []any{
		(*ExportRequest_Record)(nil),
		(*ExportRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exporter_proto_rawDesc), len(file_exporter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exporter_proto_goTypes,
		DependencyIndexes: file_exporter_proto_depIdxs,
		MessageInfos:      file_exporter_proto_msgTypes,
	}.Build()
	File_exporter_proto = out.File
	file_exporter_proto_goTypes = nil
	file_exporter_proto_depIdxs = nil
}
